version: '3'
services:
  app:
    build: .
    container_name: online-learning-platform
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=learning_platform
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=learning_platform
    ports:
      - '5432:5432'
